# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Autogo_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(968, 653)
        MainWindow.setMinimumSize(QtCore.QSize(0, 616))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/.imgs/UTools.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QMainWindow{\n"
"background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.986, fx:0.461, fy:0.511364, stop:0 rgba(156, 212, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stack_first = QtWidgets.QStackedWidget(self.centralwidget)
        self.stack_first.setGeometry(QtCore.QRect(9, 9, 950, 598))
        self.stack_first.setStyleSheet("")
        self.stack_first.setObjectName("stack_first")
        self.register_page = QtWidgets.QWidget()
        self.register_page.setObjectName("register_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.register_page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.register_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 122))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox{\n"
"border:1px solid rgb(166, 166, 166);\n"
"border-radius:5px;\n"
"margin:10px\n"
"}\n"
"QGroupBox:title {\n"
"subcontrol-origin: margin;\n"
"subcontrol-position:top left;\n"
"padding-left: 10px;\n"
"padding-right:10px;\n"
"}\n"
"QGroupBox:title {\n"
"left:20;\n"
"}\n"
"\n"
"\n"
"")
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9, 0, QtCore.Qt.AlignBottom)
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.register_page)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("QGroupBox{\n"
"border:1px solid rgb(166, 166, 166);\n"
"border-radius:5px;\n"
"margin:10px\n"
"}\n"
"QGroupBox:title {\n"
"subcontrol-origin: margin;\n"
"subcontrol-position:top left;\n"
"padding-left: 10px;\n"
"padding-right:10px;\n"
"}\n"
"QGroupBox:title {\n"
"left:20;\n"
"}\n"
"\n"
"\n"
"")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(300, -1, 300, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(30, 30))
        self.label_2.setText("")
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setPixmap(QtGui.QPixmap(":/ico/.imgs/user.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.user_id = QtWidgets.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setKerning(True)
        self.user_id.setFont(font)
        self.user_id.setStyleSheet("QLineEdit {\n"
"border:1px solid rgb(176, 221, 255);\n"
"border-radius:5px;\n"
"padding:2px 4px;\n"
"}\n"
"")
        self.user_id.setText("")
        self.user_id.setObjectName("user_id")
        self.horizontalLayout.addWidget(self.user_id)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(300, 0, 300, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setMaximumSize(QtCore.QSize(30, 30))
        self.label_3.setText("")
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setPixmap(QtGui.QPixmap(":/ico/.imgs/key.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.user_key = QtWidgets.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.user_key.setFont(font)
        self.user_key.setStyleSheet("QLineEdit {\n"
"border:1px solid rgb(176, 221, 255);\n"
"border-radius:5px;\n"
"padding:2px 4px;\n"
"}\n"
"")
        self.user_key.setEchoMode(QtWidgets.QLineEdit.Password)
        self.user_key.setObjectName("user_key")
        self.horizontalLayout_2.addWidget(self.user_key)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(305, 0, 299, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setMaximumSize(QtCore.QSize(25, 25))
        self.label_4.setText("")
        self.label_4.setTextFormat(QtCore.Qt.PlainText)
        self.label_4.setPixmap(QtGui.QPixmap(":/ico/.imgs/browser.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.browser = QtWidgets.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.browser.setFont(font)
        self.browser.setStyleSheet("QComboBox {\n"
"border:1px solid rgb(176, 221, 255);\n"
"border-radius:5px;\n"
"padding:2px 4px;\n"
"}\n"
"QComboBox::drop-down {\n"
"\n"
"border: 0px solid rgb(170, 170, 170);\n"
"\n"
"    \n"
"}\n"
"")
        self.browser.setIconSize(QtCore.QSize(0, 0))
        self.browser.setDuplicatesEnabled(False)
        self.browser.setObjectName("browser")
        self.browser.addItem("")
        self.browser.addItem("")
        self.horizontalLayout_3.addWidget(self.browser)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(370, -1, 340, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.log_in_bt = QtWidgets.QPushButton(self.groupBox_2)
        self.log_in_bt.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.log_in_bt.setFont(font)
        self.log_in_bt.setStyleSheet("QPushButton {\n"
"border:1px groove gray;\n"
"border-radius:5px;\n"
"padding:1px 4px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(170, 170, 255,80);\n"
"}\n"
"QPushButton:pressed {\n"
" background-color: rgba(170, 170, 255,225);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ico/.imgs/register.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.log_in_bt.setIcon(icon1)
        self.log_in_bt.setIconSize(QtCore.QSize(16, 16))
        self.log_in_bt.setAutoDefault(False)
        self.log_in_bt.setDefault(False)
        self.log_in_bt.setFlat(False)
        self.log_in_bt.setObjectName("log_in_bt")
        self.horizontalLayout_4.addWidget(self.log_in_bt)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem4 = QtWidgets.QSpacerItem(20, 150, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem4)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.stack_first.addWidget(self.register_page)
        self.tool_page = QtWidgets.QWidget()
        self.tool_page.setObjectName("tool_page")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tool_page)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.listWidget = QtWidgets.QListWidget(self.tool_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("QListWidget {\n"
"border:1px groove rgba(85, 170, 255, 80);\n"
"border-radius:10px;\n"
"padding:2px 4px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.523682, x2:1, y2:0.551182, stop:0 rgba(204, 229, 255, 238), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"}\n"
"\n"
"")
        self.listWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.listWidget.setLineWidth(0)
        self.listWidget.setIconSize(QtCore.QSize(25, 25))
        self.listWidget.setTextElideMode(QtCore.Qt.ElideLeft)
        self.listWidget.setFlow(QtWidgets.QListView.TopToBottom)
        self.listWidget.setGridSize(QtCore.QSize(50, 58))
        self.listWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget.setModelColumn(0)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ico/.imgs/analyzer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/ico/.imgs/autogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/ico/.imgs/review.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon4)
        self.listWidget.addItem(item)
        self.horizontalLayout_5.addWidget(self.listWidget)
        self.stack_second = QtWidgets.QStackedWidget(self.tool_page)
        self.stack_second.setStyleSheet("QPushButton {\n"
"border:1px groove gray;\n"
"border-radius:5px;\n"
"padding:2px 4px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(170, 170, 255,80);\n"
"}\n"
"QPushButton:pressed {\n"
" background-color: rgba(170, 170, 255,225);\n"
"}")
        self.stack_second.setObjectName("stack_second")
        self.code_analyzer_page = QtWidgets.QWidget()
        self.code_analyzer_page.setObjectName("code_analyzer_page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.code_analyzer_page)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_3 = QtWidgets.QGroupBox(self.code_analyzer_page)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("QGroupBox{\n"
"border:1px solid rgb(166, 166, 166);\n"
"border-radius:5px;\n"
"margin:10px\n"
"}\n"
"QGroupBox:title {\n"
"subcontrol-origin: margin;\n"
"subcontrol-position:top left;\n"
"padding-left: 10px;\n"
"padding-right:10px;\n"
"}\n"
"QGroupBox:title {\n"
"left:20;\n"
"}\n"
"\n"
"\n"
"")
        self.groupBox_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(12)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.file_path = QtWidgets.QLineEdit(self.groupBox_3)
        self.file_path.setMinimumSize(QtCore.QSize(0, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.file_path.setFont(font)
        self.file_path.setStyleSheet("QLineEdit {\n"
"border:1px solid rgb(176, 221, 255);\n"
"border-radius:5px;\n"
"padding:2px 4px;\n"
"}\n"
"")
        self.file_path.setText("")
        self.file_path.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.file_path.setDragEnabled(True)
        self.file_path.setReadOnly(True)
        self.file_path.setObjectName("file_path")
        self.horizontalLayout_6.addWidget(self.file_path)
        self.select_bt = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_bt.sizePolicy().hasHeightForWidth())
        self.select_bt.setSizePolicy(sizePolicy)
        self.select_bt.setMinimumSize(QtCore.QSize(100, 0))
        self.select_bt.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.select_bt.setFont(font)
        self.select_bt.setAutoFillBackground(False)
        self.select_bt.setStyleSheet("QPushButton {\n"
"border:1px groove gray;\n"
"border-radius:5px;\n"
"padding:2px 4px;\n"
"    background-color: rgb(241, 248, 255);\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(170, 170, 255,80);\n"
"}\n"
"QPushButton:pressed {\n"
" background-color: rgba(170, 170, 255,225);\n"
"}")
        self.select_bt.setAutoDefault(False)
        self.select_bt.setDefault(False)
        self.select_bt.setFlat(False)
        self.select_bt.setObjectName("select_bt")
        self.horizontalLayout_6.addWidget(self.select_bt)
        self.load_bt = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_bt.sizePolicy().hasHeightForWidth())
        self.load_bt.setSizePolicy(sizePolicy)
        self.load_bt.setMinimumSize(QtCore.QSize(100, 0))
        self.load_bt.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.load_bt.setFont(font)
        self.load_bt.setAutoFillBackground(False)
        self.load_bt.setStyleSheet("QPushButton {\n"
"border:1px groove gray;\n"
"border-radius:5px;\n"
"padding:2px 4px;\n"
"    background-color: rgb(241, 248, 255);\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(170, 170, 255,80);\n"
"}\n"
"QPushButton:pressed {\n"
" background-color: rgba(170, 170, 255,225);\n"
"}")
        self.load_bt.setAutoDefault(False)
        self.load_bt.setDefault(False)
        self.load_bt.setFlat(False)
        self.load_bt.setObjectName("load_bt")
        self.horizontalLayout_6.addWidget(self.load_bt)
        self.clear_bt = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_bt.sizePolicy().hasHeightForWidth())
        self.clear_bt.setSizePolicy(sizePolicy)
        self.clear_bt.setMinimumSize(QtCore.QSize(100, 0))
        self.clear_bt.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.clear_bt.setFont(font)
        self.clear_bt.setAutoFillBackground(False)
        self.clear_bt.setStyleSheet("QPushButton {\n"
"border:1px groove gray;\n"
"border-radius:5px;\n"
"padding:2px 4px;\n"
"    background-color: rgb(241, 248, 255);\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(170, 170, 255,80);\n"
"}\n"
"QPushButton:pressed {\n"
" background-color: rgba(170, 170, 255,225);\n"
"}")
        self.clear_bt.setAutoDefault(False)
        self.clear_bt.setDefault(False)
        self.clear_bt.setFlat(False)
        self.clear_bt.setObjectName("clear_bt")
        self.horizontalLayout_6.addWidget(self.clear_bt)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(46, 8, 39, 12)
        self.gridLayout.setHorizontalSpacing(16)
        self.gridLayout.setVerticalSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.func_num = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.func_num.sizePolicy().hasHeightForWidth())
        self.func_num.setSizePolicy(sizePolicy)
        self.func_num.setMinimumSize(QtCore.QSize(0, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.func_num.setFont(font)
        self.func_num.setStyleSheet("QLabel {\n"
"border:1px solid rgb(176, 221, 255);\n"
"background-color: rgb(241, 248, 255);\n"
"border-radius:5px;\n"
"padding:2px 4px;\n"
"}\n"
"")
        self.func_num.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.func_num.setText("")
        self.func_num.setObjectName("func_num")
        self.gridLayout.addWidget(self.func_num, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.global_var_num = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.global_var_num.sizePolicy().hasHeightForWidth())
        self.global_var_num.setSizePolicy(sizePolicy)
        self.global_var_num.setMinimumSize(QtCore.QSize(0, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.global_var_num.setFont(font)
        self.global_var_num.setStyleSheet("QLabel {\n"
"border:1px solid rgb(176, 221, 255);\n"
"background-color: rgb(241, 248, 255);\n"
"border-radius:5px;\n"
"padding:2px 4px;\n"
"}\n"
"")
        self.global_var_num.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.global_var_num.setText("")
        self.global_var_num.setObjectName("global_var_num")
        self.gridLayout.addWidget(self.global_var_num, 0, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 4, 1, 1)
        self.macro_num = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.macro_num.sizePolicy().hasHeightForWidth())
        self.macro_num.setSizePolicy(sizePolicy)
        self.macro_num.setMinimumSize(QtCore.QSize(0, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.macro_num.setFont(font)
        self.macro_num.setStyleSheet("QLabel {\n"
"border:1px solid rgb(176, 221, 255);\n"
"background-color: rgb(241, 248, 255);\n"
"border-radius:5px;\n"
"padding:2px 4px;\n"
"}\n"
"")
        self.macro_num.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.macro_num.setText("")
        self.macro_num.setObjectName("macro_num")
        self.gridLayout.addWidget(self.macro_num, 0, 5, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.struct_num = QtWidgets.QLabel(self.groupBox_3)
        self.struct_num.setMinimumSize(QtCore.QSize(0, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.struct_num.setFont(font)
        self.struct_num.setStyleSheet("QLabel {\n"
"border:1px solid rgb(176, 221, 255);\n"
"background-color: rgb(241, 248, 255);\n"
"border-radius:5px;\n"
"padding:2px 4px;\n"
"}\n"
"")
        self.struct_num.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.struct_num.setText("")
        self.struct_num.setObjectName("struct_num")
        self.gridLayout.addWidget(self.struct_num, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 1, 2, 1, 1, QtCore.Qt.AlignRight)
        self.enum_num = QtWidgets.QLabel(self.groupBox_3)
        self.enum_num.setMinimumSize(QtCore.QSize(0, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.enum_num.setFont(font)
        self.enum_num.setStyleSheet("QLabel {\n"
"border:1px solid rgb(176, 221, 255);\n"
"background-color: rgb(241, 248, 255);\n"
"border-radius:5px;\n"
"padding:2px 4px;\n"
"}\n"
"")
        self.enum_num.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.enum_num.setText("")
        self.enum_num.setObjectName("enum_num")
        self.gridLayout.addWidget(self.enum_num, 1, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 1, 4, 1, 1, QtCore.Qt.AlignRight)
        self.union_num = QtWidgets.QLabel(self.groupBox_3)
        self.union_num.setMinimumSize(QtCore.QSize(0, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.union_num.setFont(font)
        self.union_num.setStyleSheet("QLabel {\n"
"border:1px solid rgb(176, 221, 255);\n"
"background-color: rgb(241, 248, 255);\n"
"border-radius:5px;\n"
"padding:2px 4px;\n"
"}\n"
"")
        self.union_num.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.union_num.setText("")
        self.union_num.setObjectName("union_num")
        self.gridLayout.addWidget(self.union_num, 1, 5, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.tabWidget = QtWidgets.QTabWidget(self.code_analyzer_page)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 370))
        self.tabWidget.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setStyleSheet("QTabWidget::pane{\n"
"border:none;\n"
"}\n"
"QTabWidget::tab-bar{\n"
"left:10px\n"
"}\n"
"QTabBar::tab{\n"
"    background-color: rgb(210, 232, 254);\n"
"}\n"
"")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setObjectName("tabWidget")
        self.Function_2 = QtWidgets.QWidget()
        self.Function_2.setObjectName("Function_2")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.Function_2)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.func_items_2 = QtWidgets.QListWidget(self.Function_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.func_items_2.sizePolicy().hasHeightForWidth())
        self.func_items_2.setSizePolicy(sizePolicy)
        self.func_items_2.setMinimumSize(QtCore.QSize(256, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.func_items_2.setFont(font)
        self.func_items_2.setStyleSheet("QListWidget {\n"
"border:1px solid rgb(241, 248, 255);\n"
"border-radius:10px;\n"
"background-color: rgb(241, 248, 255);\n"
"}")
        self.func_items_2.setFrameShape(QtWidgets.QFrame.Box)
        self.func_items_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.func_items_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.func_items_2.setObjectName("func_items_2")
        self.horizontalLayout_18.addWidget(self.func_items_2)
        self.func_disp_2 = QtWidgets.QTextEdit(self.Function_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.func_disp_2.sizePolicy().hasHeightForWidth())
        self.func_disp_2.setSizePolicy(sizePolicy)
        self.func_disp_2.setMaximumSize(QtCore.QSize(16777211, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.func_disp_2.setFont(font)
        self.func_disp_2.setStyleSheet("QTextEdit {\n"
"border:1px solid rgb(241, 248, 255);\n"
"border-radius:10px;\n"
"background-color: rgb(241, 248, 255);\n"
"}")
        self.func_disp_2.setFrameShape(QtWidgets.QFrame.Box)
        self.func_disp_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.func_disp_2.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.func_disp_2.setReadOnly(False)
        self.func_disp_2.setMarkdown("")
        self.func_disp_2.setTextInteractionFlags(QtCore.Qt.TextEditorInteraction)
        self.func_disp_2.setObjectName("func_disp_2")
        self.horizontalLayout_18.addWidget(self.func_disp_2)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_18)
        self.tabWidget.addTab(self.Function_2, "")
        self.global_variable_2 = QtWidgets.QWidget()
        self.global_variable_2.setObjectName("global_variable_2")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.global_variable_2)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.global_items_2 = QtWidgets.QListWidget(self.global_variable_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.global_items_2.sizePolicy().hasHeightForWidth())
        self.global_items_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.global_items_2.setFont(font)
        self.global_items_2.setStyleSheet("QListWidget {\n"
"border:1px solid rgb(241, 248, 255);\n"
"border-radius:10px;\n"
"background-color: rgb(241, 248, 255);\n"
"}")
        self.global_items_2.setFrameShape(QtWidgets.QFrame.Box)
        self.global_items_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.global_items_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.global_items_2.setObjectName("global_items_2")
        self.horizontalLayout_20.addWidget(self.global_items_2)
        self.gloabal_disp_2 = QtWidgets.QTextEdit(self.global_variable_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.gloabal_disp_2.setFont(font)
        self.gloabal_disp_2.setStyleSheet("QTextEdit {\n"
"border:1px solid rgb(241, 248, 255);\n"
"border-radius:10px;\n"
"background-color: rgb(241, 248, 255);\n"
"}")
        self.gloabal_disp_2.setFrameShape(QtWidgets.QFrame.Box)
        self.gloabal_disp_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gloabal_disp_2.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.gloabal_disp_2.setReadOnly(False)
        self.gloabal_disp_2.setMarkdown("")
        self.gloabal_disp_2.setTextInteractionFlags(QtCore.Qt.TextEditorInteraction)
        self.gloabal_disp_2.setObjectName("gloabal_disp_2")
        self.horizontalLayout_20.addWidget(self.gloabal_disp_2)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_20)
        self.tabWidget.addTab(self.global_variable_2, "")
        self.macro_2 = QtWidgets.QWidget()
        self.macro_2.setObjectName("macro_2")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.macro_2)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.macro_items_2 = QtWidgets.QListWidget(self.macro_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.macro_items_2.sizePolicy().hasHeightForWidth())
        self.macro_items_2.setSizePolicy(sizePolicy)
        self.macro_items_2.setMinimumSize(QtCore.QSize(0, 0))
        self.macro_items_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.macro_items_2.setFont(font)
        self.macro_items_2.setStyleSheet("QListWidget {\n"
"border:1px solid rgb(241, 248, 255);\n"
"border-radius:10px;\n"
"background-color: rgb(241, 248, 255);\n"
"}")
        self.macro_items_2.setFrameShape(QtWidgets.QFrame.Box)
        self.macro_items_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.macro_items_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.macro_items_2.setObjectName("macro_items_2")
        self.horizontalLayout_22.addWidget(self.macro_items_2)
        self.macro_disp_2 = QtWidgets.QTextEdit(self.macro_2)
        self.macro_disp_2.setMinimumSize(QtCore.QSize(0, 0))
        self.macro_disp_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.macro_disp_2.setFont(font)
        self.macro_disp_2.setStyleSheet("QTextEdit {\n"
"border:1px solid rgb(241, 248, 255);\n"
"border-radius:10px;\n"
"background-color: rgb(241, 248, 255);\n"
"}")
        self.macro_disp_2.setFrameShape(QtWidgets.QFrame.Box)
        self.macro_disp_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.macro_disp_2.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.macro_disp_2.setReadOnly(False)
        self.macro_disp_2.setMarkdown("")
        self.macro_disp_2.setTextInteractionFlags(QtCore.Qt.TextEditorInteraction)
        self.macro_disp_2.setObjectName("macro_disp_2")
        self.horizontalLayout_22.addWidget(self.macro_disp_2)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_22)
        self.tabWidget.addTab(self.macro_2, "")
        self.struct_3 = QtWidgets.QWidget()
        self.struct_3.setObjectName("struct_3")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.struct_3)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.struct_items_2 = QtWidgets.QListWidget(self.struct_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.struct_items_2.sizePolicy().hasHeightForWidth())
        self.struct_items_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.struct_items_2.setFont(font)
        self.struct_items_2.setStyleSheet("QListWidget {\n"
"border:1px solid rgb(241, 248, 255);\n"
"border-radius:10px;\n"
"background-color: rgb(241, 248, 255);\n"
"}")
        self.struct_items_2.setFrameShape(QtWidgets.QFrame.Box)
        self.struct_items_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.struct_items_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.struct_items_2.setObjectName("struct_items_2")
        self.horizontalLayout_26.addWidget(self.struct_items_2)
        self.struct_disp_2 = QtWidgets.QTextEdit(self.struct_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.struct_disp_2.setFont(font)
        self.struct_disp_2.setStyleSheet("QTextEdit {\n"
"border:1px solid rgb(241, 248, 255);\n"
"border-radius:10px;\n"
"background-color: rgb(241, 248, 255);\n"
"}")
        self.struct_disp_2.setFrameShape(QtWidgets.QFrame.Box)
        self.struct_disp_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.struct_disp_2.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.struct_disp_2.setReadOnly(False)
        self.struct_disp_2.setMarkdown("")
        self.struct_disp_2.setTextInteractionFlags(QtCore.Qt.TextEditorInteraction)
        self.struct_disp_2.setObjectName("struct_disp_2")
        self.horizontalLayout_26.addWidget(self.struct_disp_2)
        self.horizontalLayout_23.addLayout(self.horizontalLayout_26)
        self.tabWidget.addTab(self.struct_3, "")
        self.enum_3 = QtWidgets.QWidget()
        self.enum_3.setObjectName("enum_3")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.enum_3)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.enum_items_2 = QtWidgets.QListWidget(self.enum_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enum_items_2.sizePolicy().hasHeightForWidth())
        self.enum_items_2.setSizePolicy(sizePolicy)
        self.enum_items_2.setMinimumSize(QtCore.QSize(0, 0))
        self.enum_items_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.enum_items_2.setFont(font)
        self.enum_items_2.setStyleSheet("QListWidget {\n"
"border:1px solid rgb(241, 248, 255);\n"
"border-radius:10px;\n"
"background-color: rgb(241, 248, 255);\n"
"}")
        self.enum_items_2.setFrameShape(QtWidgets.QFrame.Box)
        self.enum_items_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.enum_items_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.enum_items_2.setObjectName("enum_items_2")
        self.horizontalLayout_28.addWidget(self.enum_items_2)
        self.enum_disp_2 = QtWidgets.QTextEdit(self.enum_3)
        self.enum_disp_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.enum_disp_2.setFont(font)
        self.enum_disp_2.setStyleSheet("QTextEdit {\n"
"border:1px solid rgb(241, 248, 255);\n"
"border-radius:10px;\n"
"background-color: rgb(241, 248, 255);\n"
"}")
        self.enum_disp_2.setFrameShape(QtWidgets.QFrame.Box)
        self.enum_disp_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.enum_disp_2.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.enum_disp_2.setReadOnly(False)
        self.enum_disp_2.setMarkdown("")
        self.enum_disp_2.setTextInteractionFlags(QtCore.Qt.TextEditorInteraction)
        self.enum_disp_2.setObjectName("enum_disp_2")
        self.horizontalLayout_28.addWidget(self.enum_disp_2)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_28)
        self.tabWidget.addTab(self.enum_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.union_item_2 = QtWidgets.QListWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.union_item_2.sizePolicy().hasHeightForWidth())
        self.union_item_2.setSizePolicy(sizePolicy)
        self.union_item_2.setMinimumSize(QtCore.QSize(0, 0))
        self.union_item_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.union_item_2.setFont(font)
        self.union_item_2.setStyleSheet("QListWidget {\n"
"border:1px solid rgb(241, 248, 255);\n"
"border-radius:10px;\n"
"background-color: rgb(241, 248, 255);\n"
"}")
        self.union_item_2.setFrameShape(QtWidgets.QFrame.Box)
        self.union_item_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.union_item_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.union_item_2.setObjectName("union_item_2")
        self.horizontalLayout_30.addWidget(self.union_item_2)
        self.union_disp_2 = QtWidgets.QTextEdit(self.tab_2)
        self.union_disp_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.union_disp_2.setFont(font)
        self.union_disp_2.setStyleSheet("QTextEdit {\n"
"border:1px solid rgb(241, 248, 255);\n"
"border-radius:10px;\n"
"background-color: rgb(241, 248, 255);\n"
"}")
        self.union_disp_2.setFrameShape(QtWidgets.QFrame.Box)
        self.union_disp_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.union_disp_2.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.union_disp_2.setReadOnly(False)
        self.union_disp_2.setMarkdown("")
        self.union_disp_2.setTextInteractionFlags(QtCore.Qt.TextEditorInteraction)
        self.union_disp_2.setObjectName("union_disp_2")
        self.horizontalLayout_30.addWidget(self.union_disp_2)
        self.horizontalLayout_29.addLayout(self.horizontalLayout_30)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_6.addWidget(self.tabWidget)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_14 = QtWidgets.QLabel(self.code_analyzer_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMaximumSize(QtCore.QSize(58, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_31.addWidget(self.label_14)
        self.func_num_2 = QtWidgets.QLabel(self.code_analyzer_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.func_num_2.sizePolicy().hasHeightForWidth())
        self.func_num_2.setSizePolicy(sizePolicy)
        self.func_num_2.setMinimumSize(QtCore.QSize(0, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.func_num_2.setFont(font)
        self.func_num_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.func_num_2.setText("")
        self.func_num_2.setObjectName("func_num_2")
        self.horizontalLayout_31.addWidget(self.func_num_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_31)
        self.stack_second.addWidget(self.code_analyzer_page)
        self.SWDD_tool_page = QtWidgets.QWidget()
        self.SWDD_tool_page.setObjectName("SWDD_tool_page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.SWDD_tool_page)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_4 = QtWidgets.QGroupBox(self.SWDD_tool_page)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 130))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("QGroupBox{\n"
"border:1px solid rgb(166, 166, 166);\n"
"border-radius:5px;\n"
"margin:10px\n"
"}\n"
"QGroupBox:title {\n"
"subcontrol-origin: margin;\n"
"subcontrol-position:top left;\n"
"padding-left: 10px;\n"
"padding-right:10px;\n"
"}\n"
"QGroupBox:title {\n"
"left:20;\n"
"}\n"
"\n"
"\n"
"")
        self.groupBox_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(50, 26, 671, 81))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_16.setWordWrap(True)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_7.addWidget(self.groupBox_4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem5)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setContentsMargins(100, -1, 100, -1)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_15 = QtWidgets.QLabel(self.SWDD_tool_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_34.addWidget(self.label_15)
        self.review_obj_url = QtWidgets.QLineEdit(self.SWDD_tool_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.review_obj_url.sizePolicy().hasHeightForWidth())
        self.review_obj_url.setSizePolicy(sizePolicy)
        self.review_obj_url.setMinimumSize(QtCore.QSize(395, 0))
        self.review_obj_url.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.review_obj_url.setFont(font)
        self.review_obj_url.setStyleSheet("QLineEdit {\n"
"border:1px solid rgb(176, 221, 255);\n"
"border-radius:5px;\n"
"padding:2px 4px;\n"
"}\n"
"")
        self.review_obj_url.setText("")
        self.review_obj_url.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.review_obj_url.setReadOnly(False)
        self.review_obj_url.setObjectName("review_obj_url")
        self.horizontalLayout_34.addWidget(self.review_obj_url)
        self.verticalLayout_7.addLayout(self.horizontalLayout_34)
        spacerItem6 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem6)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setContentsMargins(170, -1, 198, 7)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_20 = QtWidgets.QLabel(self.SWDD_tool_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_33.addWidget(self.label_20)
        self.base_coor = QtWidgets.QLineEdit(self.SWDD_tool_page)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.base_coor.setFont(font)
        self.base_coor.setStyleSheet("QLineEdit {\n"
"border:1px solid rgb(176, 221, 255);\n"
"border-radius:5px;\n"
"padding:2px 4px;\n"
"}\n"
"")
        self.base_coor.setText("")
        self.base_coor.setReadOnly(False)
        self.base_coor.setObjectName("base_coor")
        self.horizontalLayout_33.addWidget(self.base_coor)
        self.verticalLayout_7.addLayout(self.horizontalLayout_33)
        spacerItem7 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem7)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setContentsMargins(159, -1, 199, 14)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_21 = QtWidgets.QLabel(self.SWDD_tool_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_32.addWidget(self.label_21)
        self.obj_folder = QtWidgets.QLineEdit(self.SWDD_tool_page)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.obj_folder.setFont(font)
        self.obj_folder.setStyleSheet("QLineEdit {\n"
"border:1px solid rgb(176, 221, 255);\n"
"border-radius:5px;\n"
"padding:2px 4px;\n"
"}\n"
"")
        self.obj_folder.setText("")
        self.obj_folder.setReadOnly(False)
        self.obj_folder.setObjectName("obj_folder")
        self.horizontalLayout_32.addWidget(self.obj_folder)
        self.verticalLayout_7.addLayout(self.horizontalLayout_32)
        spacerItem8 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem8)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setContentsMargins(-1, -1, -1, 8)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        spacerItem9 = QtWidgets.QSpacerItem(297, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem9)
        self.auto_bt = QtWidgets.QPushButton(self.SWDD_tool_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.auto_bt.sizePolicy().hasHeightForWidth())
        self.auto_bt.setSizePolicy(sizePolicy)
        self.auto_bt.setMinimumSize(QtCore.QSize(0, 34))
        self.auto_bt.setMaximumSize(QtCore.QSize(16777215, 27))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.auto_bt.setFont(font)
        self.auto_bt.setStyleSheet("QPushButton {\n"
"border:1px groove gray;\n"
"border-radius:5px;\n"
"padding:2px 4px;\n"
"    background-color: rgb(241, 248, 255);\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(170, 170, 255,80);\n"
"}\n"
"QPushButton:pressed {\n"
" background-color: rgba(170, 170, 255,225);\n"
"}")
        self.auto_bt.setObjectName("auto_bt")
        self.horizontalLayout_35.addWidget(self.auto_bt)
        spacerItem10 = QtWidgets.QSpacerItem(255, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem10)
        self.verticalLayout_7.addLayout(self.horizontalLayout_35)
        spacerItem11 = QtWidgets.QSpacerItem(20, 130, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem11)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.swdd_progress = QtWidgets.QProgressBar(self.SWDD_tool_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.swdd_progress.sizePolicy().hasHeightForWidth())
        self.swdd_progress.setSizePolicy(sizePolicy)
        self.swdd_progress.setMinimumSize(QtCore.QSize(200, 27))
        self.swdd_progress.setStyleSheet("")
        self.swdd_progress.setProperty("value", 0)
        self.swdd_progress.setTextVisible(False)
        self.swdd_progress.setObjectName("swdd_progress")
        self.horizontalLayout_36.addWidget(self.swdd_progress)
        self.label_17 = QtWidgets.QLabel(self.SWDD_tool_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMaximumSize(QtCore.QSize(58, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_36.addWidget(self.label_17)
        self.swdd_mention = QtWidgets.QLabel(self.SWDD_tool_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.swdd_mention.sizePolicy().hasHeightForWidth())
        self.swdd_mention.setSizePolicy(sizePolicy)
        self.swdd_mention.setMinimumSize(QtCore.QSize(0, 27))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.swdd_mention.setFont(font)
        self.swdd_mention.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.swdd_mention.setText("")
        self.swdd_mention.setObjectName("swdd_mention")
        self.horizontalLayout_36.addWidget(self.swdd_mention)
        self.verticalLayout_7.addLayout(self.horizontalLayout_36)
        self.stack_second.addWidget(self.SWDD_tool_page)
        self.Review_tool_page = QtWidgets.QWidget()
        self.Review_tool_page.setObjectName("Review_tool_page")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.Review_tool_page)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.groupBox_5 = QtWidgets.QGroupBox(self.Review_tool_page)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 130))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet("\n"
"QGroupBox{\n"
"border:1px solid rgb(166, 166, 166);\n"
"border-radius:5px;\n"
"margin:10px\n"
"}\n"
"QGroupBox:title {\n"
"subcontrol-origin: margin;\n"
"subcontrol-position:top left;\n"
"padding-left: 10px;\n"
"padding-right:10px;\n"
"}\n"
"QGroupBox:title {\n"
"left:20;\n"
"}\n"
"\n"
"\n"
"")
        self.groupBox_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_18 = QtWidgets.QLabel(self.groupBox_5)
        self.label_18.setGeometry(QtCore.QRect(42, 30, 671, 81))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_18.setWordWrap(True)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_12.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.Review_tool_page)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setItalic(True)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setStyleSheet("\n"
"QGroupBox{\n"
"border:1px solid rgb(166, 166, 166);\n"
"border-radius:5px;\n"
"margin:10px\n"
"}\n"
"QGroupBox:title {\n"
"subcontrol-origin: margin;\n"
"subcontrol-position:top left;\n"
"padding-left: 10px;\n"
"padding-right:10px;\n"
"}\n"
"QGroupBox:title {\n"
"left:20;\n"
"}\n"
"\n"
"\n"
"")
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.label_19 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_39.addWidget(self.label_19)
        self.review_link = QtWidgets.QLineEdit(self.groupBox_6)
        self.review_link.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.review_link.setFont(font)
        self.review_link.setStyleSheet("QLineEdit {\n"
"border:1px solid rgb(176, 221, 255);\n"
"border-radius:5px;\n"
"padding:2px 4px;\n"
"}\n"
"")
        self.review_link.setText("")
        self.review_link.setFrame(True)
        self.review_link.setReadOnly(False)
        self.review_link.setObjectName("review_link")
        self.horizontalLayout_39.addWidget(self.review_link)
        self.verticalLayout_10.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.label_23 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_40.addWidget(self.label_23)
        self.moderator_id = QtWidgets.QLineEdit(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moderator_id.sizePolicy().hasHeightForWidth())
        self.moderator_id.setSizePolicy(sizePolicy)
        self.moderator_id.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.moderator_id.setFont(font)
        self.moderator_id.setStyleSheet("QLineEdit {\n"
"border:1px solid rgb(176, 221, 255);\n"
"border-radius:5px;\n"
"padding:2px 4px;\n"
"}\n"
"")
        self.moderator_id.setText("")
        self.moderator_id.setFrame(True)
        self.moderator_id.setReadOnly(False)
        self.moderator_id.setObjectName("moderator_id")
        self.horizontalLayout_40.addWidget(self.moderator_id)
        self.label_24 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_40.addWidget(self.label_24)
        self.review_type = QtWidgets.QComboBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.review_type.sizePolicy().hasHeightForWidth())
        self.review_type.setSizePolicy(sizePolicy)
        self.review_type.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setItalic(True)
        self.review_type.setFont(font)
        self.review_type.setStyleSheet("QComboBox {\n"
"border:1px solid rgb(176, 221, 255);\n"
"border-radius:5px;\n"
"padding:2px 4px;\n"
"}\n"
"QComboBox::drop-down {\n"
"\n"
"border: 0px solid rgb(170, 170, 170);\n"
"\n"
"    \n"
"}\n"
"")
        self.review_type.setMaxVisibleItems(20)
        self.review_type.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.review_type.setObjectName("review_type")
        self.review_type.addItem("")
        self.review_type.addItem("")
        self.review_type.addItem("")
        self.review_type.addItem("")
        self.review_type.addItem("")
        self.review_type.addItem("")
        self.review_type.addItem("")
        self.review_type.addItem("")
        self.review_type.addItem("")
        self.review_type.addItem("")
        self.review_type.addItem("")
        self.review_type.addItem("")
        self.review_type.addItem("")
        self.review_type.addItem("")
        self.review_type.addItem("")
        self.review_type.addItem("")
        self.horizontalLayout_40.addWidget(self.review_type)
        self.verticalLayout_10.addLayout(self.horizontalLayout_40)
        self.verticalLayout_12.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.Review_tool_page)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setItalic(True)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setStyleSheet("\n"
"QGroupBox{\n"
"border:1px solid rgb(166, 166, 166);\n"
"border-radius:5px;\n"
"margin:10px\n"
"}\n"
"QGroupBox:title {\n"
"subcontrol-origin: margin;\n"
"subcontrol-position:top left;\n"
"padding-left: 10px;\n"
"padding-right:10px;\n"
"}\n"
"QGroupBox:title {\n"
"left:20;\n"
"}\n"
"\n"
"\n"
"")
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setContentsMargins(80, -1, 80, -1)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.label_22 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_41.addWidget(self.label_22)
        self.close_link = QtWidgets.QLineEdit(self.groupBox_7)
        self.close_link.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.close_link.setFont(font)
        self.close_link.setStyleSheet("QLineEdit {\n"
"border:1px solid rgb(176, 221, 255);\n"
"border-radius:5px;\n"
"padding:2px 4px;\n"
"}\n"
"")
        self.close_link.setText("")
        self.close_link.setFrame(True)
        self.close_link.setReadOnly(False)
        self.close_link.setObjectName("close_link")
        self.horizontalLayout_41.addWidget(self.close_link)
        self.verticalLayout_11.addLayout(self.horizontalLayout_41)
        self.verticalLayout_12.addWidget(self.groupBox_7)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setContentsMargins(-1, -1, -1, 50)
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_43.addItem(spacerItem12)
        self.review_bt = QtWidgets.QPushButton(self.Review_tool_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.review_bt.sizePolicy().hasHeightForWidth())
        self.review_bt.setSizePolicy(sizePolicy)
        self.review_bt.setMinimumSize(QtCore.QSize(166, 33))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.review_bt.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.review_bt.setFont(font)
        self.review_bt.setAutoFillBackground(False)
        self.review_bt.setStyleSheet("QPushButton {\n"
"border:1px groove gray;\n"
"border-radius:5px;\n"
"padding:2px 4px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(170, 170, 255,80);\n"
"}\n"
"QPushButton:pressed {\n"
" background-color: rgba(170, 170, 255,225);\n"
"}")
        self.review_bt.setObjectName("review_bt")
        self.horizontalLayout_43.addWidget(self.review_bt)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_43.addItem(spacerItem13)
        self.verticalLayout_12.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.review_progress = QtWidgets.QProgressBar(self.Review_tool_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.review_progress.sizePolicy().hasHeightForWidth())
        self.review_progress.setSizePolicy(sizePolicy)
        self.review_progress.setMinimumSize(QtCore.QSize(200, 27))
        self.review_progress.setProperty("value", 0)
        self.review_progress.setTextVisible(False)
        self.review_progress.setObjectName("review_progress")
        self.horizontalLayout_42.addWidget(self.review_progress)
        self.label_39 = QtWidgets.QLabel(self.Review_tool_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_39.sizePolicy().hasHeightForWidth())
        self.label_39.setSizePolicy(sizePolicy)
        self.label_39.setMaximumSize(QtCore.QSize(58, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_42.addWidget(self.label_39)
        self.review_mention = QtWidgets.QLabel(self.Review_tool_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.review_mention.sizePolicy().hasHeightForWidth())
        self.review_mention.setSizePolicy(sizePolicy)
        self.review_mention.setMinimumSize(QtCore.QSize(0, 27))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.review_mention.setFont(font)
        self.review_mention.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.review_mention.setText("")
        self.review_mention.setObjectName("review_mention")
        self.horizontalLayout_42.addWidget(self.review_mention)
        self.verticalLayout_12.addLayout(self.horizontalLayout_42)
        self.stack_second.addWidget(self.Review_tool_page)
        self.horizontalLayout_5.addWidget(self.stack_second)
        self.stack_first.addWidget(self.tool_page)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stack_first.setCurrentIndex(0)
        self.stack_second.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Autogo"))
        self.groupBox.setTitle(_translate("MainWindow", "About"))
        self.label_8.setText(_translate("MainWindow", "Autogo tool provides C source code to pseudocode conversion capabilities, and automatic interaction with software detailed design and review records on codebeamer."))
        self.label_9.setText(_translate("MainWindow", "Developer: Zhirun.Yu "))
        self.label.setText(_translate("MainWindow", "Version:3.0"))
        self.groupBox_2.setTitle(_translate("MainWindow", "User information"))
        self.browser.setItemText(0, _translate("MainWindow", "Chrome"))
        self.browser.setItemText(1, _translate("MainWindow", "Edge"))
        self.log_in_bt.setText(_translate("MainWindow", "Go on"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "Code Analyzer"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "SWDD tool"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "Review Record"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_3.setTitle(_translate("MainWindow", "File Information"))
        self.label_6.setText(_translate("MainWindow", "Source File:"))
        self.select_bt.setText(_translate("MainWindow", "Select"))
        self.load_bt.setText(_translate("MainWindow", "Load"))
        self.clear_bt.setText(_translate("MainWindow", "Clear"))
        self.label_5.setText(_translate("MainWindow", "Function:"))
        self.label_7.setText(_translate("MainWindow", "Global Variable:"))
        self.label_10.setText(_translate("MainWindow", "Macro Definition:"))
        self.label_11.setText(_translate("MainWindow", "Struct:"))
        self.label_12.setText(_translate("MainWindow", "Enum:"))
        self.label_13.setText(_translate("MainWindow", "Union:"))
        self.func_disp_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Function_2), _translate("MainWindow", "Function"))
        self.gloabal_disp_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Calibri\',\'Calibri\';\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.global_variable_2), _translate("MainWindow", "Global Variable"))
        self.macro_disp_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Calibri\',\'Calibri\';\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.macro_2), _translate("MainWindow", "Macro Definition"))
        self.struct_disp_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Calibri\',\'Calibri\';\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.struct_3), _translate("MainWindow", "Struct"))
        self.enum_disp_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Calibri\',\'Calibri\';\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.enum_3), _translate("MainWindow", "Enum"))
        self.union_disp_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Union"))
        self.label_14.setText(_translate("MainWindow", "Prompt:"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Description"))
        self.label_16.setText(_translate("MainWindow", "This is where the analyzed code will generate the detailed design and import Codebeamer.\n"
"1.Object URL Enter the detailed link.\n"
"2.Base Folder Enter the ID of the parent folder.\n"
"3.Object Folder Enter the ID of the generated subfolder."))
        self.label_15.setText(_translate("MainWindow", "Object URL:"))
        self.label_20.setText(_translate("MainWindow", "Base Folder:"))
        self.base_coor.setToolTip(_translate("MainWindow", "<html><head/><body><p>e.g. 23.2.1.5</p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "Object Folder:"))
        self.obj_folder.setToolTip(_translate("MainWindow", "<html><head/><body><p>e.g. 23.2.1.5</p></body></html>"))
        self.auto_bt.setToolTip(_translate("MainWindow", "<html><head/><body><p>Autogo</p></body></html>"))
        self.auto_bt.setText(_translate("MainWindow", "Start"))
        self.auto_bt.setShortcut(_translate("MainWindow", "Return"))
        self.label_17.setText(_translate("MainWindow", "Prompt:"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Description"))
        self.label_18.setText(_translate("MainWindow", "       The review, which has been submitted, link filling in here will automatically generate a record, or the record link filling in here can also automatically close the record."))
        self.groupBox_6.setTitle(_translate("MainWindow", "Review Record Build"))
        self.label_19.setText(_translate("MainWindow", "Review URL:"))
        self.label_23.setText(_translate("MainWindow", "Moderator Id:"))
        self.moderator_id.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select moderator id</p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "Review Area:"))
        self.review_type.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select review area</p></body></html>"))
        self.review_type.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.review_type.setItemText(0, _translate("MainWindow", "SYS.1 Stakeholder Requirement"))
        self.review_type.setItemText(1, _translate("MainWindow", "SYS.2 SYS Requirement Specifications"))
        self.review_type.setItemText(2, _translate("MainWindow", "SYS.3 SYS Arch Design Specifications"))
        self.review_type.setItemText(3, _translate("MainWindow", "SYS.4.1 SYS Integration Strategy"))
        self.review_type.setItemText(4, _translate("MainWindow", "SYS.4.2 SYS Integration Test Strategy"))
        self.review_type.setItemText(5, _translate("MainWindow", "SWE.1 SW Requirement Specifications"))
        self.review_type.setItemText(6, _translate("MainWindow", "SWE.2 SW Arch Design Specifications"))
        self.review_type.setItemText(7, _translate("MainWindow", "SWE.3 SW Detail Design Specifications"))
        self.review_type.setItemText(8, _translate("MainWindow", "SWE.4 SW Unit Test Specifications"))
        self.review_type.setItemText(9, _translate("MainWindow", "SWE.5 SW Integration Test Specifications"))
        self.review_type.setItemText(10, _translate("MainWindow", "SWE.5.1 SW Integration Strategy"))
        self.review_type.setItemText(11, _translate("MainWindow", "SWE.5.2 SW Integration Test Strategy"))
        self.review_type.setItemText(12, _translate("MainWindow", "SWE.6 SW Qualification Test Specifications"))
        self.review_type.setItemText(13, _translate("MainWindow", "SYS.4 SYS Integration Test Specifications"))
        self.review_type.setItemText(14, _translate("MainWindow", "SYS.5 SYS Qualification Test Specifications"))
        self.review_type.setItemText(15, _translate("MainWindow", "Others"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Review Record Close"))
        self.label_22.setText(_translate("MainWindow", "Record URL:"))
        self.review_bt.setToolTip(_translate("MainWindow", "<html><head/><body><p>Autogo</p></body></html>"))
        self.review_bt.setText(_translate("MainWindow", "Start"))
        self.label_39.setText(_translate("MainWindow", "Prompt:"))
import icon_rc
