# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Prompt.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(391, 115)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/.imgs/prompt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 78, 371, 32))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.prompt = QtWidgets.QLabel(Dialog)
        self.prompt.setGeometry(QtCore.QRect(69, 25, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setItalic(True)
        self.prompt.setFont(font)
        self.prompt.setText("")
        self.prompt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.prompt.setWordWrap(True)
        self.prompt.setObjectName("prompt")
        self.icon_2 = QtWidgets.QLabel(Dialog)
        self.icon_2.setGeometry(QtCore.QRect(23, 20, 31, 31))
        self.icon_2.setText("")
        self.icon_2.setPixmap(QtGui.QPixmap(":/ico/.imgs/提示.png"))
        self.icon_2.setScaledContents(True)
        self.icon_2.setObjectName("icon_2")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Prompt"))
import icon_rc
